### ISSUE TITLE
Window "Changes" not showing in snapper-gui on Ubuntu

### ISSUE THREAD

**Issue by MurzNN** [ricardomv/snapper-gui#12] opened 2016-01-13 07:39 UTC
Snapper-GUI installs and run successfully on Ubuntu via manual https://poisonpacket.wordpress.com/2015/06/04/installing-btrfs-snapper-gui-on-ubuntu-and-ubuntu-derivatives/

But I can't open "Changes" window for see diffs of files. When I click on this button, I see this error in console:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/snappergui-0.1-py3.4.egg/snappergui/mainWindow.py", line 160, in on_viewchanges_clicked
  File "/usr/local/lib/python3.4/dist-packages/snappergui-0.1-py3.4.egg/snappergui/changesWindow.py", line 10, in __init__
NameError: name 'GObject' is not defined
```
How I can fix this problem?

**Comment by ricardomv** [comment] 2016-01-13 09:57
Duplicate of #8

**Closed by ricardomv** 2016-01-13 09:57 UTC
Labels: duplicate
