### ISSUE TITLE
Using a limit range breaks config properties window

### ISSUE THREAD

**Issue by R1dO** [ricardomv/snapper-gui#29] opened 2017-08-23 21:17 UTC
Since 0.3.3 snapper supports the range option, see [manpage](http://snapper.io/manpages/snapper-configs.html)

When using this range in a ``*_LIMIT_*`` snapper-config parameter the properties window for any configuration is no longer available.

Snapper-gui throws the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/snappergui/application.py", line 40, in show_configs_properties
    dialog = propertiesDialog(self, self.snappergui.window)
  File "/usr/local/lib/python3.5/dist-packages/snappergui/propertiesDialog.py", line 64, in __init__
    currentTab = PropertiesTab(config)
  File "/usr/local/lib/python3.5/dist-packages/snappergui/propertiesDialog.py", line 20, in __init__
    adjustment = Gtk.Adjustment(value=int(v),
ValueError: invalid literal for int() with base 10: dbus.String('10-30')
```

**Comment by automorphism88** [comment] 2017-12-25 18:13
Duplicate of https://github.com/ricardomv/snapper-gui/issues/22

**Closed** 2018-04-02 17:29 UTC
